apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default # <-- change to match your namespace
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get","list"]